application:
  subdomain: sillytavern
  background_task: true
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://sillytavern:8000/
services:
  sillytavern:
    # ghcr.io/sillytavern/sillytavern:1.13.4
    # upstream: ghcr.io/sillytavern/sillytavern:1.18.0
    image: ghcr.1ms.run/sillytavern/sillytavern:1.18.0
    environment:
      - NODE_ENV=production
      - FORCE_COLOR=1
    binds:
      - /lzcapp/var/config:/home/node/app/config
      - /lzcapp/var/data:/home/node/app/data
      - /lzcapp/var/plugins:/home/node/app/plugins
      - /lzcapp/var/extensions:/home/node/app/public/scripts/extensions/third-party
