package: cloud.lazycat.app.sillytavern
version: 1.13.4
name: SillyTavern
description: SillyTavern 是一个用于与文本生成 LLM、图像生成引擎和 TTS 语音模型交互的本地用户界面。
min_os_version: 1.5.0
homepage: https://github.com/SillyTavern/SillyTavern
author: SillyTavern
permissions:
  required:
    - net.internet
locales:
  zh:
    name: SillyTavern
    description: SillyTavern 是一个用于与文本生成 LLM、图像生成引擎和 TTS 语音模型交互的本地用户界面。
  en:
    name: SillyTavern
    description: SillyTavern is a local interface for interacting with text-generation LLMs, image-generation engines, and TTS voice models.
